# Generated by Django 2.0.7 on 2018-08-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=10000)),
            ],
        ),
    ]
